/** Activity action constants — workspace vs project scope */

export const SCOPE = {
  WORKSPACE: 'WORKSPACE',
  PROJECT: 'PROJECT',
};

export const OBJECT_TYPES = {
  SNIPPET: 'SNIPPET',
  WIKI: 'WIKI',
  KANBAN: 'KANBAN',
  WHITEBOARD: 'WHITEBOARD',
  PROJECT: 'PROJECT',
  WORKSPACE: 'WORKSPACE',
  MEMBER: 'MEMBER',
  AI: 'AI',
};

export const WS_ACTIONS = {
  WORKSPACE_CREATED: 'WORKSPACE_CREATED',
  MEMBER_JOINED: 'MEMBER_JOINED',
  MEMBER_ROLE_CHANGED: 'MEMBER_ROLE_CHANGED',
  MEMBER_REMOVED: 'MEMBER_REMOVED',
  MEMBER_LEFT: 'MEMBER_LEFT',
  OWNERSHIP_TRANSFERRED: 'OWNERSHIP_TRANSFERRED',
  PROJECT_CREATED: 'PROJECT_CREATED',
  PROJECT_DELETED: 'PROJECT_DELETED',
  PROJECT_RENAMED: 'PROJECT_RENAMED',
  PROJECT_DESCRIPTION_UPDATED: 'PROJECT_DESCRIPTION_UPDATED',
  PROJECT_MEMBER_JOINED: 'PROJECT_MEMBER_JOINED',
  PROJECT_MEMBER_LEFT: 'PROJECT_MEMBER_LEFT',
};

export const PROJ_ACTIONS = {
  PROJECT_CREATED: 'PROJECT_CREATED',
  MEMBER_ADDED: 'MEMBER_ADDED',
  MEMBER_ROLE_CHANGED: 'MEMBER_ROLE_CHANGED',
  MEMBER_REMOVED: 'MEMBER_REMOVED',
  MEMBER_EXITED: 'MEMBER_EXITED',
  TASK_CREATED: 'TASK_CREATED',
  TASK_UPDATED: 'TASK_UPDATED',
  TASK_DELETED: 'TASK_DELETED',
  SNIPPET_CREATED: 'SNIPPET_CREATED',
  SNIPPET_DELETED: 'SNIPPET_DELETED',
  SNIPPET_METADATA_UPDATED: 'SNIPPET_METADATA_UPDATED',
  SNIPPET_UPDATED: 'SNIPPET_UPDATED',
  WIKI_CREATED: 'WIKI_CREATED',
  WIKI_DELETED: 'WIKI_DELETED',
  WIKI_METADATA_UPDATED: 'WIKI_METADATA_UPDATED',
  WIKI_UPDATED: 'WIKI_UPDATED',
  WHITEBOARD_CREATED: 'WHITEBOARD_CREATED',
  WHITEBOARD_DELETED: 'WHITEBOARD_DELETED',
  WHITEBOARD_RENAMED: 'WHITEBOARD_RENAMED',
  AI_CODE_REVIEWER: 'AI_CODE_REVIEWER',
  AI_STANDUP: 'AI_STANDUP',
  AI_SUMMARIZE: 'AI_SUMMARIZE',
  AI_GENERATE_TASKS: 'AI_GENERATE_TASKS',
  AI_BOTTLENECK: 'AI_BOTTLENECK',
};

export const KANBAN_ACTIONS = new Set([
  PROJ_ACTIONS.TASK_CREATED,
  PROJ_ACTIONS.TASK_UPDATED,
  PROJ_ACTIONS.TASK_DELETED,
]);

export const AI_ACTIONS = new Set([
  PROJ_ACTIONS.AI_CODE_REVIEWER,
  PROJ_ACTIONS.AI_STANDUP,
  PROJ_ACTIONS.AI_SUMMARIZE,
  PROJ_ACTIONS.AI_GENERATE_TASKS,
  PROJ_ACTIONS.AI_BOTTLENECK,
]);

export const TIME_RANGES = {
  '1h': 60 * 60 * 1000,
  '6h': 6 * 60 * 60 * 1000,
  '12h': 12 * 60 * 60 * 1000,
  '1d': 24 * 60 * 60 * 1000,
  '1w': 7 * 24 * 60 * 60 * 1000,
};
